kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  proxy-body-size: "500m"
  proxy-read-timeout: "3600"
  proxy-connect-timeout: "3600"
  client-max-body-size: "500m"
